### ISSUE TITLE
LisaEm 1.2.7RC4_2022.04.01 crashes on quit on macOS 10.15.7 on x86_64

### ISSUE THREAD

**Issue by fdanapfel** [rayarachelian/lisaem#13]
Hi, I wanted to get some experience on how running a Apple Lisa feels like by trying out LisaEm.

I've installed it using lisaem-1.2.7-RC4-2022.04.01-macos-10.15-x86_64.pkg  from https://lisa.sunder.net/downloads.html, and while starting the App works fine it crashes every time I select "Quit LisaEm".

Here is the crash report I get:
`
Path:                  /Applications/LisaEm.app/Contents/MacOS/lisaem-x86_64-10.15-wx3.1.5
Identifier:            net.sunder.lisaem
Version:               1.2.7-RC4_2022.04.01 (1.2.7-RC4_2022.04.01)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           lisaem-x86_64-10.15-wx3.1.5 [64270]
User ID:               501

Date/Time:             2022-09-15 22:24:37.663 +0200
OS Version:            Mac OS X 10.15.7 (19H2026)
Report Version:        12
Anonymous UUID:        4947E39D-E7A8-328B-60AE-F9EBEDDE027C

Sleep/Wake UUID:       E73AF22B-2C3E-49C9-B9E5-7F700801EF01

Time Awake Since Boot: 230000 seconds
Time Since Wake:       57000 seconds

System Integrity Protection: enabled

Crashed Thread:        Unknown

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000000000000496b
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [64270]

Backtrace not available

Unknown thread crashed with X86 Thread State (64-bit):
  rax: 0x000000020c6b3830  rbx: 0x00007f879084a000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x00007f878ee92440  rsi: 0x0000000000000000  rbp: 0x00007ffee3eb4910  rsp: 0x00007ffee3eb4818
   r8: 0x000000000000496b   r9: 0x000000000000001b  r10: 0x00007f8794900000  r11: 0x00007f879490a900
  r12: 0x0000000000000002  r13: 0x00007f878ee8a1d0  r14: 0x00007f879084a000  r15: 0x00007ffee3eb49a0
  rip: 0x000000020c5cea60  rfl: 0x0000000000010202  cr2: 0x000000000000496b
  
Logical CPU:     0
Error Code:      0x00000006 (no mapping for user data write)
Trap Number:     14

Binary images description not available

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 148510
    thread_create: 0
    thread_set_state: 0

Model: iMac14,2, BootROM 433.140.2.0.0, 4 processors, Quad-Core Intel Core i7, 3,5 GHz, 16 GB, SMC 2.15f7
Graphics: kHW_NVidiaGeForceGTX780MItem, NVIDIA GeForce GTX 780M, spdisplays_pcie_device, 4 GB
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343531533641465238412D50422020
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343531533641465238412D50422020
Memory Module: BANK 0/DIMM1, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343531533641465238412D50422020
Memory Module: BANK 1/DIMM1, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343531533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x111), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1615.7)
Bluetooth: Version 7.0.6f8, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Network Service: Ethernet, Ethernet, en0
Serial ATA Device: APPLE SSD SM0128F, 121,33 GB
Serial ATA Device: APPLE HDD ST1000DM003, 1 TB
USB Device: USB 3.0 Bus
USB Device: 4-Port USB 3.0 Hub
USB Device: USB3.0 Card Reader
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: FaceTime HD Camera (Built-in)
USB Device: 4-Port USB 2.0 Hub
Thunderbolt Bus: iMac, Apple Inc., 23.10
`

**Comment by rayarachelian** [comment]
Thanks, I'll take a look at this in the next few weeks, in the middle of some changes, but should hopefully be fixed ~RC5.

**Comment by arcanebyte** [comment]
Hello - I am sorry to say that issues reported here will not be addressed. The new home for LisaEm maintenance and future development is https://github.com/arcanebyte/lisaem.

FWIW - This is a known issue and the fix is unknown at this time.

**Comment by fdanapfel** [comment]
@arcanebyte Thanks for the notification. I'll try the version from the other repo and will report there in case I still encounter this issue.
