### ISSUE TITLE
LisaEm Crashes when installing LOS

### ISSUE THREAD

**Issue by UnTalMatias** [rayarachelian/lisaem#18]
This happened to me in RC4 and RC3. However, in the sable release this doesn't happen. What's going on?
![image](https://github.com/rayarachelian/lisaem/assets/106706551/7e1d0791-4848-47f3-ac31-78c8e38f952e)
maybe is the fact that is a _release candidate_.

**Comment by arcanebyte** [comment]
Hello - I am sorry to say that issues reported here will not be addressed. The new home for LisaEm maintenance and future development is https://github.com/arcanebyte/lisaem. - James D.
