### ISSUE TITLE
Please fix typo

### ISSUE THREAD

**Issue by Tiza59** [rayarachelian/lisaem#2]
Create a ProFile, boot from an OS instal disk ->
Create a ProFile, boot from an OS install disk

**Comment by rayarachelian** [comment]
Good catch, and thanks, I've fixed this locally, it will be updated on gihub on the next RC pre-release in the next couple of weeks depending on how long it takes me to finish the current fixes and a couple of new features.

**Comment by Tiza59** [comment]
Thank you for fixing this in RC4! Cheers.
