### ISSUE TITLE
Binary distribution fails to launch on M1 Mac

### ISSUE THREAD

**Issue by dented42** [rayarachelian/lisaem#4]
I first thought the issue was related to signing, but I'm fairly certain it's due to the strange (albeit fascinating) way you are handling multiple architectures, the launching shell script asks the system for it's architecture and doesn't have anything corresponding to ARM.

**Comment by rayarachelian** [comment]
This is (or at least should be) fixed in the unstable branch: https://github.com/rayarachelian/lisaem/blob/unstable/resources/lisaem.sh
