### ISSUE TITLE
Installation on Linux

### ISSUE THREAD

**Issue by Neelix57** [rayarachelian/lisaem#6]
I compiled version 1.2.7-unstable with wxWidgets 3.1.5. But, when I install LisaEm (as root), the script recompiles the emulator with wxWidgets 3.0 and install it, instead of install my previous compiled binaries.

I ran under the same issue on rc3a, compiled with wx3.1.4.

**Comment by Neelix57** [comment]
So, I finally put wxWidgets 3.1.4 to update-alternatives.
This time running `sudo ./build.sh install` still recompiles LisaEm before install, but with v3.1.4 and installs it.

Another thing to know, I needed to slightly modify the build.sh script in order LisaEm installs correctly system wide, as well as the  src/tools/build.sh. Both throw me an error creating the directory and skins were installed in the wrong place.

**Comment by rayarachelian** [comment]
Please see https://github.com/rayarachelian/lisaem/blob/master/README.md#compiling-wxwidgets-for-your-system  and also this example image: https://raw.githubusercontent.com/rayarachelian/lisaem/master/resources/2-build-lisaem.gif - you need to set your PATH variable to where wxWidgets is installed, which should be something like this:

export PATH=/usr/local/wx3.1.4-gtk/bin/:$PATH
export PATH=/usr/local/wx3.1.5-gtk/bin/:$PATH

The build script can't know which wxWidgets to use across all systems, you need to explicitly add the bin directory for it to your path so it can find the right wx-config binary.

What modifications did you need to make in src/tools/build.sh and build.sh?

**Comment by Neelix57** [comment]
I already set my PATH variable, but this doesn't change anything. I think this has to do with the $CYGWIN variable in conditional instruction.

For the modifications I made in the files, I will create a pull request.

**Comment by Neelix57** [comment]
Finally, I found what's wrong with the installation. I set my PATH variable with the 2 wx versions  needed for both versions of LisaEm. Keeping only the one needed for the version of LisaEm I want to compile fixed the issue.
