### ISSUE TITLE
Compilation under windows fails

### ISSUE THREAD

**Issue by Neelix57** [rayarachelian/lisaem#9]
I tried to compile LisaEm under windows 10 64bit. Both rc3a and unstable fails to compile.

RC3a: `/home/Neelix/lisaem/waitq: Aborted due to a failed job!`
Here are the [build log](https://github.com/rayarachelian/lisaem/files/6899879/rc3a_log.txt) and the [build warnings](https://github.com/rayarachelian/lisaem/files/6899878/build-warnings_rc3a.txt)

Unstable: `/home/Neelix/lisaem/bashbuild/save-restore-env.fn: line 56: /home/Neelix/lisaem/src/tools/.env-saved: No such file or directory`

Here are the [build log](https://github.com/rayarachelian/lisaem/files/6899892/unstable_log.txt) and the [build warnings](https://github.com/rayarachelian/lisaem/files/6899891/build-warnings_unstable.txt)

**Comment by rayarachelian** [comment]
Sure will check this.

Generally windows is the last os in my list that I check, so not surprised there are issues. :) My workflow there is that I download the latest available VM from here: https://developer.microsoft.com/en-us/windows/downloads/virtual-machines (sometimes they expire before a new one gets posted, in those cases I'll just wait a few weeks for the next one.)

Then from a browser, I download https://raw.githubusercontent.com/rayarachelian/lisaem/master/scripts/cygwin-install64.bat and then from the Downloads folder (right click run as administrator) on that batch file to install cygwin with all the proper tools.

Once cygwin is installed, I then clone the repo and switch to the branch I want (unstable) and then `cd scripts; ./build-wx3.1.5-cygwin-windows.sh`  then set the PATH to include /usr/local/wxWidgets-3.1.5-msw/bin like this: `export PATH=/usr/local/wxWidgets-3.1.5-msw/bin:$PATH` and then `cd ..; ./build.sh install`

And it usually works.

It looks like there was an issue handing off the top level directory which contains .env-save to the tools directory at some point.

There are other differences in the Windows build related to the serial port (limited support) and it doesn't use mmap for the DC42 library. These will be eventually dealt with, but at a much lower priority.

**Comment by rayarachelian** [comment]
found why it's breaking in windows, it's because restore-env is being called from the wrong directory. also found issues strncasecmp missing in cygwin/windows.

**Comment by rayarachelian** [comment]
also still need to disable some things for Terminalwx so it compiles cleanly under windows.

(To clarify over the weekend, I setup a new MSW10 vm, installed cygwin, compiled a custom wxWidgets and started to debug why unstable breaks on windows. I've fixed most of the low hanging bugs, the tools now compile and build successfully. Some of the serial port options such as tty and pty aren't compatible with windows and needed to be disabled, there's a couple more things preventing TerminalWx from building on windows, so debugging that.)

**Comment by rayarachelian** [comment]
this is fixed now, will be available in the unstable branch once I complete testing/debugging cycles, however, I've noticed that I've broken something else in my last attempts as LOS now throws 10707, MacWorks locks up and UniPlus also is breaking.

**Comment by rayarachelian** [comment]
most likely something in either the HLE intercepts or the profile.c code

**Comment by rayarachelian** [comment]
I've fixed almost all of these issues, was on vacation a week ago, haven't forgotten this, have one or two more things to fix and will push unstable.

**Comment by rayarachelian** [comment]
just pushed to unstable, these and a few other issues should be fixed now.

**Comment by Neelix57** [comment]
Ok Ray. I try it as soon as possible. Thank you for credit me.
